/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    partners: Partner;
    tickets: Ticket;
    products: Product;
    soldTickets: SoldTicket;
    productOrders: ProductOrder;
    jokerTickets: JokerTicket;
    messageJobs: MessageJob;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    tickets: TicketsSelect<false> | TicketsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    soldTickets: SoldTicketsSelect<false> | SoldTicketsSelect<true>;
    productOrders: ProductOrdersSelect<false> | ProductOrdersSelect<true>;
    jokerTickets: JokerTicketsSelect<false> | JokerTicketsSelect<true>;
    messageJobs: MessageJobsSelect<false> | MessageJobsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale:
    | ('false' | 'none' | 'null')
    | false
    | null
    | ('ka' | 'en' | 'ru' | 'ua')
    | ('ka' | 'en' | 'ru' | 'ua')[];
  globals: {
    site: Site;
  };
  globalsSelect: {
    site: SiteSelect<false> | SiteSelect<true>;
  };
  locale: 'ka' | 'en' | 'ru' | 'ua';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title_ka: string;
  navLabel_ka?: string | null;
  title_en?: string | null;
  navLabel_en?: string | null;
  title_ru?: string | null;
  navLabel_ru?: string | null;
  title_ua?: string | null;
  navLabel_ua?: string | null;
  /**
   * URL path, e.g. "main-stage" → /main-stage. Lowercase, no spaces.
   */
  slug: string;
  /**
   * For pages that live at a fixed React route, e.g. "/dashboard/shop". When set, menus link here instead of /{slug}.
   */
  routePath?: string | null;
  showInNav?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  navOrder?: number | null;
  featuredOnHome?: boolean | null;
  layout?:
    | (
        | {
            heading_ka: string;
            subheading_ka?: string | null;
            ctaLabel_ka?: string | null;
            heading_en?: string | null;
            subheading_en?: string | null;
            ctaLabel_en?: string | null;
            heading_ru?: string | null;
            subheading_ru?: string | null;
            ctaLabel_ru?: string | null;
            heading_ua?: string | null;
            subheading_ua?: string | null;
            ctaLabel_ua?: string | null;
            image?: (string | null) | Media;
            ctaHref?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            content_ka: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            content_en?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            content_ru?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            content_ua?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            image: string | Media;
            caption_ka?: string | null;
            caption_en?: string | null;
            caption_ru?: string | null;
            caption_ua?: string | null;
            width?: ('full' | 'contained') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image';
          }
        | {
            images?:
              | {
                  image: string | Media;
                  caption_ka?: string | null;
                  caption_en?: string | null;
                  caption_ru?: string | null;
                  caption_ua?: string | null;
                  id?: string | null;
                }[]
              | null;
            columns?: ('2' | '3' | '4') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            label_ka: string;
            label_en?: string | null;
            label_ru?: string | null;
            label_ua?: string | null;
            href: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
      )[]
    | null;
  metaTitle_ka?: string | null;
  metaDescription_ka?: string | null;
  metaTitle_en?: string | null;
  metaDescription_en?: string | null;
  metaTitle_ru?: string | null;
  metaDescription_ru?: string | null;
  metaTitle_ua?: string | null;
  metaDescription_ua?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt_ka?: string | null;
  alt_en?: string | null;
  alt_ru?: string | null;
  alt_ua?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  title_ka: string;
  excerpt_ka?: string | null;
  title_en?: string | null;
  excerpt_en?: string | null;
  title_ru?: string | null;
  excerpt_ru?: string | null;
  title_ua?: string | null;
  excerpt_ua?: string | null;
  /**
   * URL path → /news/<slug>. Lowercase, no spaces.
   */
  slug: string;
  publishedAt?: string | null;
  /**
   * Show this post in the festival landing news section.
   */
  featuredOnHome?: boolean | null;
  coverImage?: (string | null) | Media;
  layout?:
    | (
        | {
            heading_ka: string;
            subheading_ka?: string | null;
            ctaLabel_ka?: string | null;
            heading_en?: string | null;
            subheading_en?: string | null;
            ctaLabel_en?: string | null;
            heading_ru?: string | null;
            subheading_ru?: string | null;
            ctaLabel_ru?: string | null;
            heading_ua?: string | null;
            subheading_ua?: string | null;
            ctaLabel_ua?: string | null;
            image?: (string | null) | Media;
            ctaHref?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            content_ka: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            content_en?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            content_ru?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            content_ua?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            image: string | Media;
            caption_ka?: string | null;
            caption_en?: string | null;
            caption_ru?: string | null;
            caption_ua?: string | null;
            width?: ('full' | 'contained') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image';
          }
        | {
            images?:
              | {
                  image: string | Media;
                  caption_ka?: string | null;
                  caption_en?: string | null;
                  caption_ru?: string | null;
                  caption_ua?: string | null;
                  id?: string | null;
                }[]
              | null;
            columns?: ('2' | '3' | '4') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            label_ka: string;
            label_en?: string | null;
            label_ru?: string | null;
            label_ua?: string | null;
            href: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: string;
  name: string;
  /**
   * One or two sentences shown on the partners page.
   */
  description?: string | null;
  logo: string | Media;
  /**
   * Full URL, e.g. https://example.com
   */
  website?: string | null;
  featuredOnHome?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tickets".
 */
export interface Ticket {
  id: string;
  /**
   * The ticket type shown to customers.
   */
  title: string;
  /**
   * Optional details shown on the ticket card.
   */
  description?: string | null;
  priceGel: number;
  quantity: number;
  /**
   * Format: YYYY-MM-DD.
   */
  eventDate?: string | null;
  location?: string | null;
  /**
   * Only Active / Sold out tickets appear on the public site.
   */
  status: 'draft' | 'active' | 'sold_out';
  /**
   * Optional link to an external ticketing page.
   */
  saleUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  title: string;
  description?: string | null;
  priceGel: number;
  /**
   * Upload the product photo.
   */
  image?: (string | null) | Media;
  /**
   * Auto-filled from the uploaded image.
   */
  imageUrl?: string | null;
  category?: string | null;
  isVip?: boolean | null;
  sizes?:
    | {
        size: string;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  status: 'draft' | 'active' | 'sold_out';
  updatedAt: string;
  createdAt: string;
}
/**
 * Read-only ticket purchases created by the payment flow.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "soldTickets".
 */
export interface SoldTicket {
  id: string;
  personalNumber?: string | null;
  email?: string | null;
  name?: string | null;
  surname?: string | null;
  amount?: number | null;
  status?: ('pending' | 'paid' | 'failed' | 'scanned') | null;
  originalTicketId?: string | null;
  eventName?: string | null;
  eventDate?: string | null;
  location?: string | null;
  paidAt?: string | null;
  scannedAt?: string | null;
  scannedBy?: string | null;
  createdAt: string;
  /**
   * Payment gateway order id.
   */
  pgOrderId?: number | null;
  pgPassword?: string | null;
  qrCode?: string | null;
  failedAt?: string | null;
  failReason?: string | null;
  updatedAt: string;
}
/**
 * Read-only merch orders created by the product payment flow.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productOrders".
 */
export interface ProductOrder {
  id: string;
  productId?: string | null;
  productTitle?: string | null;
  size?: string | null;
  name?: string | null;
  email?: string | null;
  phone?: string | null;
  amount?: number | null;
  status?: ('pending' | 'paid' | 'collected' | 'failed') | null;
  qrCode?: string | null;
  createdAt: string;
  paidAt?: string | null;
  collectedAt?: string | null;
  /**
   * Payment gateway order id.
   */
  pgOrderId?: number | null;
  pgPassword?: string | null;
  failedAt?: string | null;
  failReason?: string | null;
  updatedAt: string;
}
/**
 * Read-only mirror of paid Joker ticket purchases.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jokerTickets".
 */
export interface JokerTicket {
  id: string;
  personalNumber?: string | null;
  email?: string | null;
  name?: string | null;
  surname?: string | null;
  amount?: number | null;
  status?: string | null;
  originalTicketId?: string | null;
  eventName?: string | null;
  eventDate?: string | null;
  location?: string | null;
  paidAt?: string | null;
  scannedAt?: string | null;
  createdAt: string;
  updatedAt: string;
}
/**
 * Read-only outgoing message queue used by ticket emails.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messageJobs".
 */
export interface MessageJob {
  id: string;
  email?: string | null;
  subject?: string | null;
  type?: string | null;
  status?: string | null;
  attempts?: number | null;
  lastError?: string | null;
  ticketId?: string | null;
  createdAt: string;
  updatedAt: string;
  sentAt?: string | null;
  payload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'partners';
        value: string | Partner;
      } | null)
    | ({
        relationTo: 'tickets';
        value: string | Ticket;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'soldTickets';
        value: string | SoldTicket;
      } | null)
    | ({
        relationTo: 'productOrders';
        value: string | ProductOrder;
      } | null)
    | ({
        relationTo: 'jokerTickets';
        value: string | JokerTicket;
      } | null)
    | ({
        relationTo: 'messageJobs';
        value: string | MessageJob;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title_ka?: T;
  navLabel_ka?: T;
  title_en?: T;
  navLabel_en?: T;
  title_ru?: T;
  navLabel_ru?: T;
  title_ua?: T;
  navLabel_ua?: T;
  slug?: T;
  routePath?: T;
  showInNav?: T;
  navOrder?: T;
  featuredOnHome?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              heading_ka?: T;
              subheading_ka?: T;
              ctaLabel_ka?: T;
              heading_en?: T;
              subheading_en?: T;
              ctaLabel_en?: T;
              heading_ru?: T;
              subheading_ru?: T;
              ctaLabel_ru?: T;
              heading_ua?: T;
              subheading_ua?: T;
              ctaLabel_ua?: T;
              image?: T;
              ctaHref?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content_ka?: T;
              content_en?: T;
              content_ru?: T;
              content_ua?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              image?: T;
              caption_ka?: T;
              caption_en?: T;
              caption_ru?: T;
              caption_ua?: T;
              width?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              images?:
                | T
                | {
                    image?: T;
                    caption_ka?: T;
                    caption_en?: T;
                    caption_ru?: T;
                    caption_ua?: T;
                    id?: T;
                  };
              columns?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              label_ka?: T;
              label_en?: T;
              label_ru?: T;
              label_ua?: T;
              href?: T;
              id?: T;
              blockName?: T;
            };
      };
  metaTitle_ka?: T;
  metaDescription_ka?: T;
  metaTitle_en?: T;
  metaDescription_en?: T;
  metaTitle_ru?: T;
  metaDescription_ru?: T;
  metaTitle_ua?: T;
  metaDescription_ua?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title_ka?: T;
  excerpt_ka?: T;
  title_en?: T;
  excerpt_en?: T;
  title_ru?: T;
  excerpt_ru?: T;
  title_ua?: T;
  excerpt_ua?: T;
  slug?: T;
  publishedAt?: T;
  featuredOnHome?: T;
  coverImage?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              heading_ka?: T;
              subheading_ka?: T;
              ctaLabel_ka?: T;
              heading_en?: T;
              subheading_en?: T;
              ctaLabel_en?: T;
              heading_ru?: T;
              subheading_ru?: T;
              ctaLabel_ru?: T;
              heading_ua?: T;
              subheading_ua?: T;
              ctaLabel_ua?: T;
              image?: T;
              ctaHref?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content_ka?: T;
              content_en?: T;
              content_ru?: T;
              content_ua?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              image?: T;
              caption_ka?: T;
              caption_en?: T;
              caption_ru?: T;
              caption_ua?: T;
              width?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              images?:
                | T
                | {
                    image?: T;
                    caption_ka?: T;
                    caption_en?: T;
                    caption_ru?: T;
                    caption_ua?: T;
                    id?: T;
                  };
              columns?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              label_ka?: T;
              label_en?: T;
              label_ru?: T;
              label_ua?: T;
              href?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  logo?: T;
  website?: T;
  featuredOnHome?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tickets_select".
 */
export interface TicketsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  priceGel?: T;
  quantity?: T;
  eventDate?: T;
  location?: T;
  status?: T;
  saleUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  priceGel?: T;
  image?: T;
  imageUrl?: T;
  category?: T;
  isVip?: T;
  sizes?:
    | T
    | {
        size?: T;
        quantity?: T;
        id?: T;
      };
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "soldTickets_select".
 */
export interface SoldTicketsSelect<T extends boolean = true> {
  id?: T;
  personalNumber?: T;
  email?: T;
  name?: T;
  surname?: T;
  amount?: T;
  status?: T;
  originalTicketId?: T;
  eventName?: T;
  eventDate?: T;
  location?: T;
  paidAt?: T;
  scannedAt?: T;
  scannedBy?: T;
  createdAt?: T;
  pgOrderId?: T;
  pgPassword?: T;
  qrCode?: T;
  failedAt?: T;
  failReason?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productOrders_select".
 */
export interface ProductOrdersSelect<T extends boolean = true> {
  id?: T;
  productId?: T;
  productTitle?: T;
  size?: T;
  name?: T;
  email?: T;
  phone?: T;
  amount?: T;
  status?: T;
  qrCode?: T;
  createdAt?: T;
  paidAt?: T;
  collectedAt?: T;
  pgOrderId?: T;
  pgPassword?: T;
  failedAt?: T;
  failReason?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jokerTickets_select".
 */
export interface JokerTicketsSelect<T extends boolean = true> {
  id?: T;
  personalNumber?: T;
  email?: T;
  name?: T;
  surname?: T;
  amount?: T;
  status?: T;
  originalTicketId?: T;
  eventName?: T;
  eventDate?: T;
  location?: T;
  paidAt?: T;
  scannedAt?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messageJobs_select".
 */
export interface MessageJobsSelect<T extends boolean = true> {
  email?: T;
  subject?: T;
  type?: T;
  status?: T;
  attempts?: T;
  lastError?: T;
  ticketId?: T;
  createdAt?: T;
  updatedAt?: T;
  sentAt?: T;
  payload?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt_ka?: T;
  alt_en?: T;
  alt_ru?: T;
  alt_ua?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Festival landing hero text and the public navigation menu.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site".
 */
export interface Site {
  id: string;
  heroBadge_ka?: string | null;
  heroTitle_ka?: string | null;
  heroTagline_ka?: string | null;
  heroBadge_en?: string | null;
  heroTitle_en?: string | null;
  heroTagline_en?: string | null;
  heroBadge_ru?: string | null;
  heroTitle_ru?: string | null;
  heroTagline_ru?: string | null;
  heroBadge_ua?: string | null;
  heroTitle_ua?: string | null;
  heroTagline_ua?: string | null;
  menu?:
    | {
        page: string | Page;
        label_ka?: string | null;
        label_en?: string | null;
        label_ru?: string | null;
        label_ua?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site_select".
 */
export interface SiteSelect<T extends boolean = true> {
  heroBadge_ka?: T;
  heroTitle_ka?: T;
  heroTagline_ka?: T;
  heroBadge_en?: T;
  heroTitle_en?: T;
  heroTagline_en?: T;
  heroBadge_ru?: T;
  heroTitle_ru?: T;
  heroTagline_ru?: T;
  heroBadge_ua?: T;
  heroTitle_ua?: T;
  heroTagline_ua?: T;
  menu?:
    | T
    | {
        page?: T;
        label_ka?: T;
        label_en?: T;
        label_ru?: T;
        label_ua?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}