export const navItems = [
  { labelKey: "mainStage", href: "/dashboard/mainStage" },
  { labelKey: "qvevri", href: "/dashboard/qvevriStage" },
  { labelKey: "technoQvevri", href: "/dashboard/technoQvevri" },
  { labelKey: "lineup", href: "/dashboard/lineUp" },
  { labelKey: "joker", href: "/dashboard/jokerTicket" },
  { labelKey: "ukrainianDay", href: "/dashboard/ukrainianPage" },
  { labelKey: "fourStages", href: "/dashboard/four-stages" },
  { labelKey: "ourStory", href: "/dashboard/our-story" },
  { labelKey: "ticket", href: "/dashboard/tickets" },
  { labelKey: "mission", href: "/dashboard/mission" },
  { labelKey: "partners", href: "/dashboard/partners" },
  { labelKey: "news", href: "/dashboard/news" },
  { labelKey: "foodZone", href: "/dashboard/food-zone" },
  { labelKey: "contactUs", href: "/dashboard/contact" },
  { labelKey: "festivalRulesTerms", href: "/dashboard/rulesAndTerms" },
];
